### ISSUE TITLE
loadFutureTexture makes main thread hang

### ISSUE THREAD

**Issue by knnnrd** [Samsung/GearVRf#807] opened 2016-08-12 09:59 UTC
Hi, I'm trying to load large bitmap textures async from the local file system using the following code:
`Future<GVRTexture> tex = mGVRContext.loadFutureTexture(new GVRAndroidResource(path),GVRContext.LOWEST_PRIORITY, GVRCompressedTexture.SPEED);
GVRMaterial mat = new GVRMaterial(mGVRContext);
mat.setMainTexture(tex);`

The problem is that head tracking stops working for a second, so the image stays still. Is there a way to fix this?

Thanks in advance

**Comment by liaxim** [comment] 2016-08-12 14:30
When do you execute this code? From onInit or some time later?

**Comment by knnnrd** [comment] 2016-08-12 16:27
Some time later. More specifically, right after I receive a broadcast from a background service that downloads the images and saves them to local storage.

I tried to put this code in an android AsyncTask but that didn't help much either.
Would it help to store ASTC or ETC2 compressed images on the server, download those and use them instead? If there is a way to just use bitmaps, that would be preferred of course.

**Comment by liaxim** [comment] 2016-08-12 18:24
We don't have anything in the framework that can help much in this case. You should definitely use one of the compressed texture formats since the process will be more efficient.

**Comment by knnnrd** [comment] 2016-08-13 17:59
Ok I will try that then.. If I may ask, why does [http://docs.gearvrf.org/org/gearvrf/GVRContext.html#loadFutureTexture(org.gearvrf.GVRAndroidResource)](this) say that I can use this function to load a texture asynchronously if it apparently not really does? Or do I misunderstand what async loading means? Just wondering.
Thanks

**Comment by thomasflynn** [comment] 2016-08-15 17:20
The the file i/o of decoding an loading into memory is done asynchronously.  Ultimately, glTexImage2D or glCompressedTexImage2D needs to be called on the GL thread to give the image to the GPU.  It's the allocation on the GPU and upload of the texture that may be the cause of the pausing.  If your images are the same size, it may be faster to use one GVRBitmapTexture and then call update() with the new bitmap.

**Comment by liaxim** [comment] 2016-08-17 23:40
@knnnrd How big are the files you are trying to load? How many?

**Comment by knnnrd** [comment] 2016-08-23 06:56
I was trying to load files of about 7MB which were 8k resolution. The amount doesn't really matter I think because I was mostly loading them one at a time with a few seconds between each load, but during my testing it was about 5 images.

**Comment by liaxim** [comment] 2016-08-23 15:54
Ok, these are pretty big so they would definitely cause stuttering. We don't have anything out of the box that will help in this case (loading them after the initial startup). We will look into it but I can't give a timeline.

**Comment by liaxim** [comment] 2016-08-24 22:32
Since we understand the problem but can't do anything about it right now, would be ok to close this issue? I opened https://github.com/Samsung/GearVRf/issues/809 instead. Thanks

**Closed** 2016-08-24 22:40 UTC
Labels: question
