### ISSUE TITLE
Widget viewer demos broken

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#1819] opened 2018-04-07 01:40 UTC
Anything that uses the Widget Viewer now puts a big black rectangle in front that obscures the application. If you take all references to the Widget plugin out, the black rectangle goes away. The widget plugin appears to be broken.

**Comment by NolaDonato** [comment] 2018-04-10 17:49
Yes, both are obscured.  I am using Oculus on S8

**Comment by liaxim** [comment] 2018-04-10 19:28
Please let me know how https://github.com/gearvrf/GearVRf-Demos/pull/596 works for you. So far I am seeing problems only the demos.

**Comment by Caprica666** [comment] 2018-04-11 01:33
gvr-widgetviewer and gvr-modelviewer2 still show black screens. My S8 has Android 8 installed. I will try it with an older OS.

**Comment by liaxim** [comment] 2018-04-11 15:07
Ok, so the problem is specifically with Android O.

**Comment by liaxim** [comment] 2018-04-11 18:36
Problem with the Z-order of the two SurfaceViews - ours and gdx's.

**Comment by liaxim** [comment] 2018-04-18 15:08
Fix merged

**Closed by liaxim** 2018-04-18 15:08 UTC
Labels: bug
