### ISSUE TITLE
App exiting while run on DayDream device

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1802] opened 2018-03-19 20:11 UTC
Hi,
I built the app for both Samsung gear device(oculus) and Google daydream device.
The app input events perfectly fine on Samsung gear device(oculus) including swipe, click and back key events.
But on DayDream headset i can see the weird behavior, tapping any Google Controller(remote) key consecutive two times making my app exit to device home screen.

My implementation logic.
I am dispatching received touch events from GVRCursorController(GVRCursorController.getMotionEvent()) to my GVRSceneObject. 

Please suggest me a way to do for DayDream devices if my approach is wrong.

**Comment by spakanati123** [comment] 2018-03-19 20:27
This is log trace:
```

03-20 01:55:31.481 15066-15066/com.qp.vrdemo D/ViewRootImpl@485f199[VRDemoHomeActivity]: MSG_WINDOW_FOCUS_CHANGED 0
03-20 01:55:31.556 15066-15066/com.qp.vrdemo V/Configuration:  needToUpdateOverlays
03-20 01:55:31.556 15066-15066/com.qp.vrdemo I/chatty: uid=10364(u0_a364) com.qp.vrdemo identical 2 lines
03-20 01:55:31.556 15066-15066/com.qp.vrdemo V/Configuration:  needToUpdateOverlays
03-20 01:55:31.624 15066-15066/com.qp.vrdemo D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.qp.vrdemo/com.qp.vrdemo.VRDemoHomeActivity@9b9e936@1) com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{9b9e936 V.E...... ........ 0,0-2678,1440}
03-20 01:55:31.625 15066-15066/com.qp.vrdemo D/SurfaceView: surfaceDestroyed 1 com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{9b9e936 V.E...... ........ 0,0-2678,1440}
03-20 01:55:31.638 15066-15066/com.qp.vrdemo D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.qp.vrdemo/com.qp.vrdemo.VRDemoHomeActivity@79339a4@1) android.opengl.GLSurfaceView{79339a4 V.E...... ........ 0,0-2678,1440}
03-20 01:55:31.644 15066-15066/com.qp.vrdemo D/SurfaceView: surfaceDestroyed 1 android.opengl.GLSurfaceView{79339a4 V.E...... ........ 0,0-2678,1440}
03-20 01:55:31.684 15066-15066/com.qp.vrdemo D/SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.qp.vrdemo/com.qp.vrdemo.VRDemoHomeActivity@9b9e936@1) true false com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{9b9e936 I.E...... ........ 0,0-2678,1440}
03-20 01:55:31.689 15066-15066/com.qp.vrdemo D/SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.qp.vrdemo/com.qp.vrdemo.VRDemoHomeActivity@79339a4@1) true false android.opengl.GLSurfaceView{79339a4 I.E...... ........ 0,0-2678,1440}
03-20 01:55:31.698 15066-15234/com.qp.vrdemo D/OpenGLRenderer: eglDestroySurface = 0xc57e6258
03-20 01:55:31.755 15066-15066/com.qp.vrdemo D/ViewRootImpl@485f199[VRDemoHomeActivity]: Relayout returned: old=[0,0][2678,1440] new=[0,0][2678,1440] result=0x5 surface={valid=false 0} changed=true
03-20 01:55:32.363 15066-19230/com.qp.vrdemo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-20 01:55:32.364 15066-19230/com.qp.vrdemo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-20 01:55:32.801 15066-15066/com.qp.vrdemo D/ViewRootImpl@485f199[VRDemoHomeActivity]: Relayout returned: old=[0,0][2678,1440] new=[0,0][2678,1440] result=0x1 surface={valid=false 0} changed=false
03-20 01:55:32.956 15066-15066/com.qp.vrdemo I/GVRActivity: onDestroy b1418f0
03-20 01:55:33.144 15066-15066/com.qp.vrdemo E/BpSurfaceComposerClient: Failed to transact (-1)
03-20 01:55:33.145 15066-15066/com.qp.vrdemo D/SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.qp.vrdemo/com.qp.vrdemo.VRDemoHomeActivity@9b9e936@1) com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{9b9e936 I.E...... ........ 0,0-2678,1440}
03-20 01:55:33.146 15066-15066/com.qp.vrdemo E/BpSurfaceComposerClient: Failed to transact (-1)
03-20 01:55:33.196 15066-15066/com.qp.vrdemo E/BpSurfaceComposerClient: Failed to transact (-1)
03-20 01:55:33.197 15066-15066/com.qp.vrdemo D/SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.qp.vrdemo/c
```

**Comment by spakanati123** [comment] 2018-03-19 21:01
I can able to reproduce the issue with Sample app as well.
Sample app link:
https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-immersivepedia/app

build the above sample app for DayDream only by removing the below meta tag from the manifest 
  <!-- <meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/>
**Steps to reproduce:**
Once app lanches click the remote centre pad 2 or 3 times continusly and observe the app exiting to home screen.

Sample app log trace:

```
03-20 02:24:59.044 2262-2262/org.gearvrf.immersivepedia D/ViewRootImpl@3dfa2de[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
03-20 02:24:59.122 2262-2262/org.gearvrf.immersivepedia V/Configuration:  needToUpdateOverlays
03-20 02:24:59.122 2262-2262/org.gearvrf.immersivepedia V/Configuration:  needToUpdateOverlays
03-20 02:24:59.123 2262-2262/org.gearvrf.immersivepedia V/Configuration:  needToUpdateOverlays
03-20 02:24:59.124 2262-2262/org.gearvrf.immersivepedia V/Configuration:  needToUpdateOverlays
03-20 02:24:59.151 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - org.gearvrf.immersivepedia/org.gearvrf.immersivepedia.MainActivity@7c5f878@1) com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{7c5f878 V.E...... ........ 0,0-2678,1440}
03-20 02:24:59.153 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: surfaceDestroyed 1 com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{7c5f878 V.E...... ........ 0,0-2678,1440}
03-20 02:24:59.157 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - org.gearvrf.immersivepedia/org.gearvrf.immersivepedia.MainActivity@7772fb6@1) android.opengl.GLSurfaceView{7772fb6 V.E...... ........ 0,0-2678,1440}
03-20 02:24:59.164 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: surfaceDestroyed 1 android.opengl.GLSurfaceView{7772fb6 V.E...... ........ 0,0-2678,1440}
03-20 02:24:59.197 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: BG hide() Surface(name=Background for - SurfaceView - org.gearvrf.immersivepedia/org.gearvrf.immersivepedia.MainActivity@7c5f878@1) true false com.google.vr.ndk.base.GvrLayoutImpl$AsyncReprojectionSurfaceView{7c5f878 I.E...... ........ 0,0-2678,1440}
03-20 02:24:59.198 2262-2262/org.gearvrf.immersivepedia D/SurfaceView: BG hide() Surface(name=Background for - SurfaceView - org.gearvrf.immersivepedia/org.gearvrf.immersivepedia.MainActivity@7772fb6@1) true false android.opengl.GLSurfaceView{7772fb6 I.E...... ........ 0,0-2678,1440}
03-20 02:24:59.205 2262-2444/org.gearvrf.immersivepedia D/OpenGLRenderer: eglDestroySurface = 0xcee96fc0
03-20 02:24:59.232 2262-2262/org.gearvrf.immersivepedia D/ViewRootImpl@3dfa2de[MainActivity]: Relayout returned: old=[0,0][2678,1440] new=[0,0][2678,1440] result=0x5 surface={valid=false 0} changed=true
03-20 02:24:59.745 2262-2262/org.gearvrf.immersivepedia D/ViewRootImpl@3dfa2de[MainActivity]: Relayout returned: old=[0,0][2678,1440] new=[0,0][2678,1440] result=0x1 surface={valid=false 0} changed=false
03-20 02:25:00.103 2262-2262/org.gearvrf.immersivepedia D/ViewRootImpl@3dfa2de[MainActivity]: Relayout returned: old=[0,0][2678,1440] new=[0,0][2678,1440] result=0x1 surface={valid=false 0} changed=false
03-20 02:25:00.382 2262-2262/org.gearvrf.immersivepedia I/GVRActivity: onDestroy 3575534
```

**Comment by spakanati123** [comment] 2018-03-20 19:27
@liaxim , @bohuang3d

**Comment by bohuang3d** [comment] 2018-03-20 21:13
You mean tapping _any_ key whether be the home, app button, or the clickable touchpad?

For the clickable touchpad, does it happen for touching twice, or does it happen for clicking twice?

Does time delay between consecutive tapping matter?

**Comment by spakanati123** [comment] 2018-03-21 05:44
@bohuang3d I tried with touchpad and back key and issue can reproducible very easily. 
And also i tried making the delay between each click event 500 msec delay(half a second) but still the issue can reproducible.
- Yes , touching twice or more than that only issue can be observed, single tap issue not observed(but sometimes i can see app hanging).

The issue can be reproduced very easily on provided sample apps(i tried gvr-immeresivepedia). 
I hope u have the Google DayDream headset.

**Comment by liaxim** [comment] 2018-03-21 15:26
@spakanati123 Could you please override GVRMain.onBackPress and return always true from it? Does it help?

**Comment by spakanati123** [comment] 2018-03-21 16:52
@liaxim i tried that already but no luck, If you look at logs GVRActivity onDestroy() calling irrespective of the onBackPress() callback.

**Comment by liaxim** [comment] 2018-03-22 19:26
Reproduced. Looking into it.

**Comment by spakanati123** [comment] 2018-03-22 19:59
@liaxim and also i observed GVRMain.onBackPress calling two times for one click event on Samsung Gear headset.

**Comment by liaxim** [comment] 2018-03-22 22:01
@spakanati123 Are you able to reproduce with the gvr-controller sample app? How much memory does your app use (``adb shell dumpsys meminfo <your-apps-package-name>``)?

**Comment by liaxim** [comment] 2018-03-23 15:12
@spakanati123 I don't know the root cause yet but calling ``sendEventsToActivity(false)`` on the controller object is a workaround. For example:

```
        gvrContext.getInputManager().selectController(new GVRInputManager.ICursorControllerSelectListener()
        {
            public void onCursorControllerSelected(GVRCursorController newController, GVRCursorController oldController)
            {
                GazeController cursor = GazeController.get();

                if (cursor == null)
                {
                    new GazeController(newController);
                }
                else
                {
                    newController.setCursor(cursor.getCursor());
                }
                mController = newController;
                newController.addPickEventListener(pickHandler);
                newController.sendEventsToActivity(false);
            }
        });
```

**Comment by liaxim** [comment] 2018-03-23 16:16
We are generating hits on the top left corner "X" close button Daydream places automatically. Looks like might have to ``sendEventsToActivity(false)`` always for Daydream.

**Comment by NolaDonato** [comment] 2018-03-23 19:55
I am not sure what that will break. I put this in so that applications could process touch events from the controller. Otherwise, the app doesn't get anything.

**Comment by liaxim** [comment] 2018-03-23 21:28
What apps need those events? Do apps care for more than the key events?

**Comment by NolaDonato** [comment] 2018-03-23 21:43
Apps that use the Android gesture detector need a stream of Android motion events from the controller. That is what sendEventsToActivity does.

**Comment by liaxim** [comment] 2018-03-23 22:13
Will look into emitting IActivityEvents.onTouchEvent instead of directly dispatching and will update the affected demos. Thanks.

**Comment by liaxim** [comment] 2018-04-04 14:34
Merged the fix. Planning to close the ticket in few days if there are no further comments. Thanks.

**Closed** 2018-04-17 16:17 UTC
Labels: bug
