### ISSUE TITLE
ndk-build.cmd error

### ISSUE THREAD

**Issue by Joshf17000548** [Samsung/GearVRf#619] opened 2016-06-18 22:19 UTC
Please help. Been looking all over and can not resolve my problem. I'm trying to build the Framework project in android 2.1.2

When I clean my project I get the following error message:
Could not find property 'ndkbuild' on task ':framework:buildNative'.

My build.gradle file looks as follows:
`import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'com.android.library'

android {
    compileSdkVersion 21
    buildToolsVersion '23.0.3'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 19

        ndk {
            moduleName "gvrf"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    sourceSets.main {
        java.srcDirs = ['src/main/java']
        jni.srcDirs = [] // no auto generation of Android.mk
        jniLibs.srcDir 'src/main/libs' // pre-compiled libraries
    }

    task buildNative(type: Exec) {
        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }
		
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            ndkbuild += 'ndk-build.cmd'
        } else {
            ndkbuild += 'ndk-build'
        }

        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }

        commandLine ndkbuild, '-C', file('src/main').absolutePath, '-j', 16//, 'NDK_DEBUG=1'
    }

    task cleanNative(type: Exec) {
        def ndkbuild = ""
        if (rootProject.hasProperty("ANDROID_NDK_HOME")) {
            ndkbuild = rootProject.property("ANDROID_NDK_HOME")
            ndkbuild += '/'
        }
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            ndkbuild += 'ndk-build.cmd'
        } else {
            ndkbuild += 'ndk-build'
        }

        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }
        commandLine ndkbuild, '-C', file('src/main').absolutePath, '-j', 16, 'clean'
    }

    clean.dependsOn 'cleanNative'

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn buildNative
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile fileTree(dir: 'src/main/libs', include: ['*.jar'])
}`

**Comment by deepakrawat22** [comment] 2016-06-20 03:20
@Joshf17000548 which platform are you using. If using windows you need to replace 'ndk-build.cmd' to full path to ndk directory in below code:

`if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        ndkbuild += 'ndk-build.cmd'
    } else {
        ndkbuild += 'ndk-build'
    }`

Let us know if the problem is still there.

**Comment by liaxim** [comment] 2016-06-20 14:59
Your build.gradle is not exactly the same as the one in the repo. You seem to be missing a variable definition (note the very first line here):

```
    def ndkbuild = ""
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        ndkbuild += 'ndk-build.cmd'
    } else {
        ndkbuild += 'ndk-build'
    }
```

Please double-check the gradle files and let us know your results. Thanks.

**Comment by Joshf17000548** [comment] 2016-06-20 23:24
Thank you for the quick reply. 

I had everything working again this morning, but when I tried to import another sample app, I got this error:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/gearvrf/ActivityHandler;

I've tried everything to get it away, but no luck.

**Comment by liaxim** [comment] 2016-06-21 14:24
@Joshf17000548 Sounds like you may have added the gvrf classes more than once to your classpath. Please check what local changes you may have made. Or alternatively clone the repos to a new location and try again without modifications. You can use the instructions from https://github.com/Samsung/GearVRf/wiki/Build%20Tips to specify the Oculus and the NDK directories.

**Comment by Joshf17000548** [comment] 2016-06-21 21:55
That works. Thank you very much!

Not all hero's wear capes.

**Comment by liaxim** [comment] 2016-06-21 21:59
Glad to hear it. Can we close the issue?

**Comment by Joshf17000548** [comment] 2016-06-21 22:00
Yes. Thank you.

**Closed** 2016-06-22 14:12 UTC
Labels: build issue
