### ISSUE TITLE
Problems when attaching GVRPicker to scene models

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1339] opened 2017-07-28 14:03 UTC
Hi, I've been using code for my picker object based on the sample in gvr-controller (See the onCursorControllerAdded function in SampleMain.java).

I've hit various erratic problems which seem to be timing dependent. Depending on exactly what objects I attach to my picker, how I load them, and some random timing variations I can get anything from no visible picker, a partially visible picker or even occasionally a "Fatal signal 11" crash.

The easiest way I've found to reproduce this on my phone, a Galaxy S7, is to run the gvr-controller sample app. Then when it's up and running press the Back or Home button on the controller, click Cancel on the 'Exit to Oculus home' dialog that appears. This returns you to the sample app, I'm finding most of the time I don't see the picker anymore, and the log output is reporting 200+ of the following error messages per second while I move the controller around:

07-28 14:50:16.167 28974-4502/org.gearvrf.sample.controller E/gvrf: renderMesh::renderMaterialShader error: GL_INVALID_OPERATION

If you have trouble reproducing let me know and I'll put together a modified version of the sample app that reproduces the issue more often. This is reproducible using the latest build of GearVRf I pulled this morning, as well as on the previous version based on code pulled at the end of May.

**Comment by bohuang3d** [comment] 2017-07-31 21:18
Yes I can reproduce it. We will take a look

**Comment by NolaDonato** [comment] 2017-07-31 21:34
Jon Reynolds can help too, he is familiar with the controller code

**Comment by bohuang3d** [comment] 2017-07-31 22:06
That would be great. So far I see things on the JNI engine side:

Line 666 of gl_renderer.cpp
at end of the function there is
checkGLError("renderMesh::renderMaterialShader");

To narrow down where the GL_INVALID_OPERATION happens in this long function, I think we should add more such checks throughout. This GL error could be making the controller's graphics disappear.

**Comment by NolaDonato** [comment] 2017-07-31 22:37
Are we sure the GL error is the problem? It is possible that Jon's matrix locking OR for physics will fix this issue. The controller code runs in a separate thread and modifies the model matrix which is used in computing picking.

**Comment by bohuang3d** [comment] 2017-07-31 22:45
It's a possibility, as any GLerror on glDrawElements() or glBindVertexArray() in that function negates a draw

And these calls are dependent on data fed to it. Let's try the matrix/physics fixes when they become available and maybe they will fix it

**Comment by roshanch** [comment] 2017-07-31 23:18
do you see any shader compilation errors?

**Comment by NolaDonato** [comment] 2017-07-31 23:24
I have seen this error before. I tried to track it down by putting checkGLError everywhere but was unsuccessful. If you put checkGLError in renderCamera you may find it gets called on the first frame.

**Comment by liaxim** [comment] 2017-08-01 14:28
The static mesh cache in the asset loader is the cause feeding bad meshes. If you hit Oculus home and return back to the app, usually the process is not killed and any writable static state can and usually does become a problem.

Should be fixed by https://github.com/Samsung/GearVRf/issues/1349.

**Comment by NolaDonato** [comment] 2017-08-01 17:07
I am questioning the need for the mesh cache. I left it there but I think it might be better to make it a model cache based on the resource like we do with textures. We should discuss this next week.

**Comment by SteveGreatApe** [comment] 2017-08-17 13:00
Hi, I've tried out the Mesh Cache fix you've pushed for this bug. It's a partial fix, but I've still got another problem with the model I attach to the Picker. It's a bit complicated of scenario to explain, with some side issues on the way, but bear with me.

To reproduce it make sure developer mode is disabled, put the phone into the Gear headset and run the gvr-controller app.

Put the headset on check everything looks okay, but if you try picking up the objects you can only select the ones outside the main block or at the top left cube in the block. This seems to be an issue with the picker Z-Pos used by the test app.

Now take the headset off and wait around half a minute, then put the headset back on. This triggers the controller to be detached and re-attached. You should see a pair of Log messages saying "Got the orientation remote controller". There's actually two identical logging lines being used on add and remove, I've modified them to say ADDED/REMOVED, so I get.

```
08-17 13:23:38.153 30526-31160/org.gearvrf.sample.controller D/SampleMain: Got the orientation remote controller REMOVED
08-17 13:23:38.381 30526-31160/org.gearvrf.sample.controller D/SampleMain: Got the orientation remote controller ADDED
```

Now what I'm finding is I can see two copies of picker objects, both the green cube and sphere have been re-created closer to the camera. Out of interest I made a tweak to the code use a static float to set the yPos of the object, I increase the yPos each time the controller is re-created. I can then see that each time more and more new objects are being added at the ever increasing y position.

Also I noticed now you can select any item, it seems the picker Z-pos has shifted back closer to the camera along with the picker scene objects.

I think part of what we see here is a bug in the test app, you need to fix that first to see the main issue next. Modify onCursorControllerRemoved as follows:

```
        @Override
        public void onCursorControllerRemoved(GVRCursorController gvrCursorController) {
            if (gvrCursorController.getControllerType() == GVRControllerType.CONTROLLER) {
                android.util.Log.d(TAG, "Got the orientation remote controller REMOVED");
                gvrCursorController.removeControllerEventListener(controllerEventListener);
                gvrCursorController.resetSceneObject();
                sphere = null;
            }
        }
```
        
Now you don't get the duplicated objects, but you are stuck with the problem of not being able to pick up most of the objects.

Next up is the main bug I'm hitting, to re-create the problem I get in my app you need to add an extra scene object to the picker. Use this function to add a GVRCylinderSceneObject.

```
        private void addCylinder(GVRSceneObject parent) {
            GVRCylinderSceneObject.CylinderParams cylinderParams = new GVRCylinderSceneObject.CylinderParams();
            cylinderParams.Height = DEPTH;
            cylinderParams.TopRadius = 0.02f;
            cylinderParams.BottomRadius = 0.01f;
            GVRCylinderSceneObject cylinder1 = new GVRCylinderSceneObject(mGVRContext, cylinderParams);
            GVRMaterial material = new GVRMaterial(cylinder1.getGVRContext());
            material.setDiffuseColor(0.5f, 0.6f, 0.7f, 1.0f);
            GVRRenderData renderData = cylinder1.getRenderData();
            renderData.setAlphaBlend(true);
            renderData.setShaderTemplate(GVRPhongShader.class);
            renderData.setMaterial(material);
            renderData.setRenderingOrder(GVRRenderData.GVRRenderingOrder.OVERLAY + 1);
            cylinder1.getRenderData().setCullFace(GVRRenderPass.GVRCullFaceEnum.Front);
            GVRTransform transform = cylinder1.getTransform();
            transform.setRotationByAxis(-90.0f, 1.0f, 0.0f, 0.0f);
            transform.setPosition(0.0f, 0.0f, DEPTH / 2);
            parent.addChildObject(cylinder1);
        }
```

Call the new function in onCursorControllerAdded() after adding the existing sphere and cube:

```
                    ...
                    parent.addChildObject(cube);
                    addCylinder(parent); // <========= Add extra call here
                    mPicker.setPickRay(0.0f, 0.0f, 0.0f, 0.0f, 0.0f, DEPTH);
                    ...
```

What I find now is the new Cylinder appears when I first run the app, but when I take the headset off and wait half a minute and put it back on my cylinder doesn't get re-created, even though the two original green objects do.

**Comment by liaxim** [comment] 2017-08-28 16:44
@SteveGreatApe Which version of the framework are you using? I highly recommend trying the latest master. What is your test phone?

I can't reproduce not being able to pick some of the scene objects in gvr-controller nor the duplication. @J0Nreynolds has made a number of fixes and improvements over the last couple of months.

Please make your changes on top of the latest framework and demos and let us know what is the situation. Thanks.

**Comment by liaxim** [comment] 2017-08-28 16:48
Pull request for the gvr-controller app to fix the handling of the cursorControllerRemoved event: https://github.com/gearvrf/GearVRf-Demos/pull/505.

**Comment by SteveGreatApe** [comment] 2017-08-29 12:44
Thanks, I've grabbed the latest Master of Framework and Demo apps.

The gvr-controller demo app has completely changed how it shows the picker, it's now using the new GVRGearControllerSceneObject class which appears to be just what I've been after all this time that I've been trying to get my picker to work properly. I can't reproduce the problem now with that change in place.

I've switched to using this in my code as well now, all seems fine so far. I'll let you know if I hit any problems with it.

**Comment by liaxim** [comment] 2017-08-29 14:00
Awesome. Can we close this issue for now?

**Comment by SteveGreatApe** [comment] 2017-08-31 13:24
As long as the old method of attaching a model to the Picker is deprecated then it should be okay to close this. But if not then there could still be a problem lurking there that will hit any one using it.

**Comment by liaxim** [comment] 2017-09-18 16:26
@SteveGreatApe Will close then in few days if there are no objections. @NolaDonato is in the process of reworking our controller support and subsequently the APIs. The first pull request is https://github.com/Samsung/GearVRf/pull/1416.

**Closed** 2017-09-22 18:16 UTC
Labels: bug
