### ISSUE TITLE
External Views framerate

### ISSUE THREAD

**Issue by mkeblx** [Samsung/GearVRf#227] opened 2015-08-20 00:53 UTC
I'm finding the ability to map live Android views onto in-world geometry handy but a desired update rate of 60fps seems out of reach with current implementation. Ex.: a 1024x1024 view @ 60fps is ~2Gbps cpu->gpu. Are there any other approaches that you see working at this time with current implementation of SurfaceTexture, etc?

**Comment by thomasflynn** [comment] 2015-08-20 21:40
that's a good question.  i'm open to suggestions.

**Comment by mkeblx** [comment] 2015-08-28 21:44
I've played with this: 
https://github.com/ArtemBogush/AndroidViewToGLRendering
and testing out I can get quite high performance and acceptable update rate, ~30-60fps where currently limited to a few fps now.

Looking at the this and gearvrf they are almost exactly the same in overall methodology but something slightly/subtly different.

Also: http://www.felixjones.co.uk/neo%20website/Android_View/

**Comment by ragner** [comment] 2015-10-05 11:54
Hi,
@mkeblx Do you have any example implemented over GearVRF and Android OpenGL that we could use to compare the performance?

@thomasflynn  I have seen some REFRESH_INTERVAL at GVRWebViewSceneObject.
Is there another logic at GearVRF limiting its refresh interval?

**Comment by thomasflynn** [comment] 2015-10-05 18:21
@mkeblx, i think the key difference between the implementation with AndroidViewToGLRendering and our implementation is that the other one derives its own WebView to override draw(), in that draw() it uses the canvas provided by the AndroidViewToGLRenderer class rather than the passed in draw.  in the AndroidViewToGLRenderer, it only calls SurfaceTexture.updateTexImage() in onDrawFrame() and nothing else.

In our implementation, for every onDrawFrame(), the WebView is asked to draw and that is followed by the updateTexImage().

In other words, onDrawFrame() happens in the GL thread, draw() generally happens in the UI thread.  Our implementation is calling draw() inside onDrawFrame().  I'm not sure how much of a problem that is, but that seems to be the difference between the two implementations.  

if there was nothing new for the WebView to draw we would be wasting cycles asking it to draw.  but if the WebView was drawing something moving anyway (an animation, video, whatever), i don't immediately see where what we currently have would be worse, unless the WebView itself takes too many milliseconds to draw.

@ragner, REFRESH_INTERVAL is the only thing limiting its refresh that we're doing.

**Comment by mkeblx** [comment] 2015-10-05 20:59
@ragner What's your email? m.blix@samsung.com

**Comment by mkeblx** [comment] 2015-10-06 01:04
@thomasflynn Is there any downside to the other approach? If not performance, complexity, etc. I'm not sure where the additional perf issue would be for a View updating every frame but I think it exists. 

@ragner The native mobile Oculus SDK examples may contain some similar View handling, but that might just be view video specific. 

One recent example of performant View texture usage is the Netflix app which is primarily their existing Android TV UI on a quad. It's a basic approach others with build-out Android apps will likely take, if they can do it out of the box with gearvrf it would be a fast path for them.

Netflix: http://techblog.netflix.com/2015/09/john-carmack-on-developing-netflix-app.htm
>The core Netflix application uses two Android Surfaces – one for the user interface layer, and one for the decoded video layer. To present these in VR I needed to be able to reference them as OpenGL textures, so the process was: create an OpenGL texture ID, use that to initialize a SurfaceTexture object, then use that to initialize a Surface object that could be passed to Netflix.

>For the UI surface, this worked great -- when the Netflix code does a swapbuffers, the VR code can have the SurfaceTexture do an update, which will latch the latest image into an EGL external image, which can then be texture mapped onto geometry by the GPU.

**Comment by thomasflynn** [comment] 2015-10-06 03:34
the only drawback i can see to the other approach is complexity.  we would need to user to derive their own webview to implement draw() themselves so they can use the SurfaceView provided by the WebViewSceneObject and we'd have to expose a way to get that SurfaecView in WebViewSceneObject.  This wouldn't be too hard an experiment to try.  I'm kinda swamped right now.  any volunteers?  I can help code review it for ya so you at least know if you're on the right track.

**Comment by ragner** [comment] 2015-10-06 14:26
@thomasflynn with your code review, I would like to work on it.  May I?

My email is ragner.n@samsung.com

**Comment by thomasflynn** [comment] 2015-10-06 17:30
Go for it.  You won't need collaborator access.  You can just fork the repo, clone your own fork, create a branch, work in there, when ready do a pull-request here.  If you want me to go over it before you do the pull-request, you can send me a link to your branch and I'll be able to comment on it.

once you do the pull-request everyone watching this repo will get an email and we'll be able to review and merge it.

**Comment by ragner** [comment] 2015-10-06 18:02
Ok,
thank you.

**Comment by ragner** [comment] 2015-10-08 21:46
@thomasflynn I have finished at https://github.com/ragner/GearVRf/tree/issue-227
that branch also add a RenderableView sample that shows 
how to use GVRViewSceneObject.
The sample is based on  https://github.com/ArtemBogush/AndroidViewToGLRendering
Could you please, review it?

**Comment by ragner** [comment] 2015-10-08 21:52
After launch the RenderableView  sample, you can scroll the Web page and select some link using the oculus touchpad.

**Comment by thomasflynn** [comment] 2015-10-08 23:19
Just reviewed the code, haven't tried running it yet.  Couple comments:
- don't need the import for WebView in GVRViewSceneObject.java :)
- should look how to modify the WebViewSceneObject to use this method so there aren't multiple conflicting ways of doing the same thing.
- don't necessarily need a separate sample for this.  could just modify the existing scene-objects sample.

**Comment by ragner** [comment] 2015-10-23 15:21
Hi @thomasflynn,
thank you.
I have other try:
https://github.com/ragner/GearVRf/commits/issue-227

**Comment by ragner** [comment] 2015-10-23 15:27
Basic sample, of how to use it
https://github.com/ragner/GearVRf/commits/renderable

**Comment by liaxim** [comment] 2015-10-27 21:42
Looks pretty good. Do you still plan to keep the gvr-renderableview sample? You can go ahead and create a pull request.

**Comment by ragner** [comment] 2015-10-28 01:04
My initial plan was to keep gvr-renderableview as a sample of how to use all GVRView's types, but @thomasflynn asked me just to modify the existing scene-objects. Up to now I just use it to test my implementations.

**Comment by ragner** [comment] 2015-10-28 01:12
My next plan is implement a GVRTextView to fix the issue #246 
Does it looks ok for you @liaxim?

**Comment by liaxim** [comment] 2015-10-28 19:30
Yes, it looks pretty good to me.

**Comment by ragner** [comment] 2015-11-03 21:50
Does anyone have comment to #291?

**Comment by liaxim** [comment] 2015-11-04 13:39
Hi, @thomasflynn is back. Let's give him a chance to look at it.

**Comment by thomasflynn** [comment] 2015-11-09 21:10
#291 is merged.  close this issue?

**Closed** 2015-11-09 21:21 UTC

**Comment by freshindee** [comment] 2016-08-09 06:29
How I can show a normal android apps( like mobile version of word application) inside a VR app screen , not in whole screen, it must be like a front screen like in Netflix. (I can open word app from VR app , but I cannot put it in the front screen, it comes to whole screen). 

Please any idea.

**Comment by ayogan2** [comment] 2018-02-05 18:10
Hello, 
I'm using release 4.0 and still experience reduced frame rate for the texture(only about 4fps). Is there a trick to getting this fixed version of renderable? The same application seems considerably faster on PhoneCastVR though. Is there something I'm missing?

**Comment by liaxim** [comment] 2018-02-05 18:31
@ayogan2 There have been improvements when it comes to handling Android views. Can you share more details about what do you have rendered into the external texture? How frequently it gets updated? Could you share a sample project that exhibits the problem? Thanks.

**Comment by ayogan2** [comment] 2018-02-05 23:15
@liaxim Thank you so much for your quick response. Eliminating the webview from the example, definitely helps speeding up. Still, there seems to be a good difference between a regular Android application and its equivalent running within GearVRf.

My application is in some sense, a "trackpad for android".  I have a regular 2D android application with traditional Android UI (grid of buttons). A virtual cursor, controlled by a networked remote device (say a trackpad), moves around to interact with the UI elements. The cursor movement update rate is based on the rate at which the networked positions arrive, which I would say is in the 16 millisecond range for the most part. When I run the application as a regular Android app, I get really good performance, update rate and little latency. Similar performance in PhonecastVR. When I run the same application within GearVR as a renderable view, the texture update rate seems to be reduced, introducing some stutter. 

Sharing my application can be tricky, but I put together couple bare bones examples that can provide a glimpse into the issue. 
https://github.com/ayogan2/timeticker (a simple 2D application with a ticking textview that is updated every 4 milliseconds)
https://github.com/ayogan2/gvr-renderableview-fps (the equivalent GearVRf application).
I don't have an exact way of measuring the refresh rate of the texture, but comparing the rate at which the textview is changing between the two applications should give a sense of how quickly the texture is updating. 

In my application it seems more pronounced than here. I'm from SEA. If you have a Samsung email id, I could send you some screengrabs of my application and comparisons between the different cases.

Thanks in advance for your help!

**Comment by liaxim** [comment] 2018-02-06 19:48
@ayogan2 It is m.marinov@samsung.com

**Comment by liaxim** [comment] 2018-02-07 17:39
Hi, attaching videos of what I am seeing. Having trouble making out the last two digits on the right in the regular app case but I kind of can in the gvrf app. Is this what you are referring to?

[videos.zip](https://github.com/Samsung/GearVRf/files/1704110/videos.zip)

**Comment by liaxim** [comment] 2018-02-07 17:39
@ayogan2 And it would be best if you could open a new issue for your problem. Thanks.

**Comment by liaxim** [comment] 2018-02-07 19:58
@ayogan2 We are limited by the Surface/SurfaceTexture apis we rely on. What you could do is use lower-resolution views. Attaching one more video. Does it look better? I changed the buffer width and height for the surface texture to be 1/4th of view's.

[video2.zip](https://github.com/Samsung/GearVRf/files/1704533/video2.zip)

**Comment by ayogan2** [comment] 2018-02-07 21:55
Hi @liaxim Thank you so much for looking into this issue and getting back to me. Yes, your observation about not being able to read the last two digits is representative of how quickly the texture is updating. When the cursor needs to update at this rate, it also faces the same issue. 

I am emailing you some screen recordings that showcase the issue at hand. The texture update rate in GVR is in general slower than the 2D equivalent. The issue is compounded in that during some runs, the texture update gets progressively slower as time progress and reaches down to 1-2fps (which will be in the video I email you).

I can try reducing the resolution and see if that helps. After our email discussion, I can also open a new issue for this problem if needed.
