### ISSUE TITLE
GVRModelSceneObject as child with animations

### ISSUE THREAD

**Issue by retterdesdialogs** [Samsung/GearVRf#1556] opened 2017-10-20 15:36 UTC
Im using the gvr-controls example to build a button. But instead using textures I want to use a fbx model.

So what I did is 

```
public GVRModelSceneObject mButton;
GVRContext context;

public MenuButton(GVRContext gvrContext)  {
        super(gvrContext);

        context = gvrContext;

        try {

            GVRMesh sMesh = gvrContext.createQuad(4,2);

            attachRenderData(new GVRRenderData(gvrContext));
            getRenderData().setMaterial(new GVRMaterial(gvrContext));
            getRenderData().getMaterial().setOpacity(0f);
            getRenderData().setMesh(sMesh);

            mButton = gvrContext.getAssetLoader().loadModel("models/menu/MenuButton.fbx");
            mButton.getTransform().setPosition(0,0,0);
            mButton.getTransform().rotateByAxis(90,1,0,0);

            addChildObject(mButton);

            getRenderData().setRenderingOrder(10000);

            attachComponent(new GVRMeshCollider(gvrContext, false));

        } catch (IOException e) {
            e.printStackTrace();
        }

    }
```

In the MainScene I add the button with

```
MenuButton menuButton = new MenuButton(gvrContext);

        menuButton.setTouchAndGesturelistener(new TouchAndGestureImpl() {
            @Override
            public void singleTap() {

                super.singleTap();

            }
        });

        menuButton.getTransform().setPosition(0,0,-7);
        gvrContext.getMainScene().addSceneObject(menuButton);
```

At first this works pretty well and I can see my button and also the gainedFocus(), lostFocus() and so on are working.

But if I start the an animation in the gainedFocus() focus for example, the mButton (the child of menuButton) is jumping to position 0,0,0 in the scene and animates.

- So adding the GVRModelSceneObject as child to menuButton on position 0,0,0 is working.
- Set the position for the menuButton to 0,0,-7 in the scene is working
- Starting the animation will put the mButton to 0,0,0 in the scene, while the menuButton keeps his y: -7 position in the scene.

It looks like the animationEngine tooks the child position 0,0,0 as position to start the animation in the scene.

Is this a bug or how I can handle this?

Any help would be great.

**Comment by NolaDonato** [comment] 2017-10-20 21:46
What animation are you talking about? I do not see the animation so it is very difficult to tell why it starts at 0,0,0. If the animation has 0,0,0 as the position that could be the reason it starts there. The animation will change the position of your object.

If you want an animation to move an object relative to another object, you can parent the animated object to the other one. For example, you can put an object at 0,0,-7 and then put the button under that and the animation will be relative to 0,0,-7

**Comment by liaxim** [comment] 2017-10-23 23:14
@retterdesdialogs Did @NolaDonato 's suggestion work for you? We can be of more help if you could share a test app.

**Comment by liaxim** [comment] 2017-10-23 23:36
@apjagdale is reproducing the problem and is working on it.

**Comment by apjagdale** [comment] 2017-10-25 18:16
@retterdesdialogs We have a workaround for this until we fix this issue. I have modified the gvr-meshanimation demo. 
Links:
https://github.com/apjagdale/GearVRf-Demos/tree/animationIssue1556
https://github.com/apjagdale/GearVRf-Demos/blob/3e65e0f840585bc529bb61881cc9d46ae6695415/gvr-meshanimation/app/src/main/java/org/gearvrf/gvrmeshanimation/MeshAnimationMain.java

Following is the description:
-menuButton is the root which has a mesh of a quad to it. It also has a child at index 0 which is the FBX model(TRex). Whenever you want to make changes to the Trex model do menuButton.getChildByIndex(0) or have its reference in your class and use it.

**Comment by NolaDonato** [comment] 2017-10-25 19:08
I will work on fixing this in 4.1. I looked into it and it appears the animation code looks at the nodes above the animated character and putting in extra nodes can affect the animation. This is incorrect but will probably require rewriting some of the animation import code. Some of the operations it does at run time should really be done during asset import and should be independent of where you put the animated object in the scene.

**Comment by liaxim** [comment] 2018-07-06 15:20
@retterdesdialogs Planning to close the issue in few days.

**Closed** 2018-07-12 18:24 UTC
Labels: bug
