### ISSUE TITLE
GVRViewSceneObject on click not fired

### ISSUE THREAD

**Issue by ageofish** [Samsung/GearVRf#1786] opened 2018-03-13 06:06 UTC
When running the gvr_events example in the headset, the buttons doesn't seem to be pressed (not highlighted), also OnClick events are not fired.
When running the app on the phone, everything works with tapping on the screen.

Seems like a bug?
I override onTouch and was able to get the event in headset, and onCursorControllerSelected seems to be selecting GAZE controller in the headset correctly, any ideas?

**Comment by liaxim** [comment] 2018-03-13 20:41
Yes, a bug. Was able to reproduce. Thanks for letting us know. We'll have it fixed.

**Comment by liaxim** [comment] 2018-03-16 17:59
@ageofish There is a fix in https://github.com/Samsung/GearVRf/pull/1799. There are still some issues but gvr-events should work ok enough.

**Comment by liaxim** [comment] 2018-03-21 15:17
@ageofish I believe the issue is addressed. Will close this ticket in few days.

**Closed** 2018-03-29 15:37 UTC
Labels: bug
