### ISSUE TITLE
Updating mesh problem

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#772] opened 2016-08-04 17:10 UTC
I am trying to update the GVRMesh of an GVRSceneObject, it worked in a previous version of GearVRf. It seems that the mesh size will not be updated In the current version. The native address is different.

I am setting an new mesh, with a new size like:

`sceneObject.getRenderData().setMesh(newMesh);`

Getting native address:
`sceneObject.getRenderData().getMesh().getNative()`

I am not sure if it's a bug or I am updating the GVRMesh in a wrong way...

**Comment by liaxim** [comment] 2016-08-04 17:13
It is very likely a bug, thank you for letting us know.

Are you building the framework yourself?

**Comment by QKnows** [comment] 2016-08-04 17:15
Yes, I am building the framework by myself, using Android Studio.

**Comment by Vittalbabu** [comment] 2016-08-04 17:31
I will look at this issue.

Regards,


-          Vittal

**Comment by Vittalbabu** [comment] 2016-08-08 23:09
@QKnows  I am seeing a couple of errors with setMesh under different scenarios -- where the result of setMesh() is not what is expected. Could you share the relevant portions of your sample relating to setMesh() -- the sequence of calls from creating GVRSceneObject, GVRRenderData and the 2 GVRMesh instances? I want to see if we have additional issues with setMesh().

**Comment by QKnows** [comment] 2016-08-09 08:26
Hello @Vittalbabu,

here is a code snippet to show you the behavior of setMesh issue.

I want to change the mesh size in case of some event, i.e. the touch event. 

        public void init() {
                // Load some sample textures...
                final GVRTexture parentTexture = this.getGVRContext().loadTexture(new
                         GVRAndroidResource(this.getGVRContext(), "parentTexture.png"));
                final GVRTexture child1Texture = this.getGVRContext().loadTexture(new 
                        GVRAndroidResource(this.getGVRContext(), "child1Texture.png"));
                final GVRTexture child2Texture = this.getGVRContext().loadTexture(new 
                        GVRAndroidResource(this.getGVRContext(), "child2Texture.png"));

                // Create the meshes...
                final GVRMesh parentMesh = this.getGVRContext().createQuad(50.0f, 30.0f);
                final GVRMesh child1Mesh = this.getGVRContext().createQuad(30.0f, 15.0f);
                final GVRMesh child2Mesh = this.getGVRContext().createQuad(5.0f, 5.0f);
                final GVRMesh child2Mesh2 = this.getGVRContext().createQuad(140.0f, 35.0f);

                // Create the objects...
                final GVRSceneObject parent = new GVRSceneObject(this.getGVRContext(), 
                        parentMesh, parentTexture);
                final GVRSceneObject child1 = new GVRSceneObject(this.getGVRContext(), 
                        child1Mesh, child1Texture);
                final GVRSceneObject child2 = new GVRSceneObject(this.getGVRContext(), 
                        child2Mesh,  child2Texture);

                // Set the render mask
                parent.getRenderData().setRenderMask(
                        GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);
                child1.getRenderData().setRenderMask(
                        GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);
                child2.getRenderData().setRenderMask(
                        GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);

                // Add the children to the parent object...
                parent.addChildObject(child1);
                parent.addChildObject(child2);

                // Translate the objects...
                parent.getTransform().translate(0.0f, 0.0f, -50.0f);
                child1.getTransform().translate(0.0f, 0.0f, 0.1f);
                child2.getTransform().translate(0.0f, -30.0f, 0.1f);

                // Add the parent to the main scene.
                this.mainScene.addSceneObject(parent);

                // Setting mesh2 here, would work fine...
                //child2.getRenderData().setMesh(child2Mesh2);

                this.child2 = child2;
                this.child2Mesh2 = child2Mesh2;
                this.child2Mesh1 = child2Mesh;
        }

        @Override
        public void onStep() {
                if (this.mIsTouched) {
                    Log.d(TAG, "Setting mesh 2");
                    this.child2.getRenderData().setMesh(this.child2Mesh2);
                    this.mIsTouched = false;
                }
        }

**Comment by Vittalbabu** [comment] 2016-08-09 17:31
Thanks -- my scenario was similar. I will update this thread once I have a fix.

**Comment by Vittalbabu** [comment] 2016-08-09 23:45
@QKnows My issue was a bug in my sample code -- I didn't take into account the drawMode value for the RenderData instances of the two SceneObject instances which was showing the incorrect rendering after setMesh(). I am not able to reproduce the issue in my sample code and will test with your scenario. I have changed the meshes and the new size is used in rendering.

I will test with your scenario. Is it possible to get a screenshot showing the issue?

Thanks.

**Comment by QKnows** [comment] 2016-08-18 08:21
Hallo @Vittalbabu,
my code looks like the example I posted before. I initialize the mesh for my child2 when I create the texture. When some event occurs, i.e. onFocus, I change the mesh but the texture has still the size of the initial mesh.
I don't understand what you are doing with the drawMode, should I set or change it at some point?

Thanky you for your efforts....

**Comment by Vittalbabu** [comment] 2016-08-18 18:22
@QKnows  Could you send a screen shot showing this?

To render, we have to set the mesh as well as renderData. For example, RenderData holds drawMode which controls how the mesh data (the indices in the mesh) is used to create the output. If you are not setting it then that is likely not to be an issue.

Looking at a screen shot will help to visualize the problem.

Thanks.

**Comment by liaxim** [comment] 2016-09-08 16:05
@QKnows Do you have something for us? We need the extra information @Vittalbabu requested to be able to proceed. Thanks.

**Comment by QKnows** [comment] 2016-09-13 12:52
@Vittalbabu sorry but I don't understand what drawMode I should set. I am using code like my code snippet before. If the user looks at the object I am changing the mesh like

child2.getRenderData().setMesh(child2Mesh2);

The initial mesh is "empty (gvrContext.createQuad(0.0f, 0.0f);

But there won't be any resize of the mesh. So how could I solve that? Or do I need different objects with different meshes?

**Comment by roshanch** [comment] 2016-09-13 13:26
@QKnows could you try with latest framework? If the issue is still there, we will update you soon. Thanks.

**Comment by thomasflynn** [comment] 2017-03-08 02:10
Hi there @QKnows, it looks like this conversation went stale a long time ago, but I wanted to check in anyway.  I coded up a sample to match what you have here in the report:

https://github.com/thomasflynn/GearVRf-Demos/tree/mesh/gvr-meshchange

And that seems to work as expected with the latest top of trunk.  Let me know if there is something different I need to do to reproduce the issue or if the issue seems to be fixed.
Thanks!

**Comment by thomasflynn** [comment] 2017-03-10 01:25
I'll leave this open for comments until Monday (the 13th).  if there aren't any new comments, i suggest we close this issue at that point.

**Comment by thomasflynn** [comment] 2017-03-13 17:41
Ok, this seems to be working.  If someone sees a similar problem, please open a new issue.  Thanks.

**Closed by thomasflynn** 2017-03-13 17:41 UTC
Labels: bug
