### ISSUE TITLE
Problem with gaze controller onTouchStart/onTouchEnd events

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1695] opened 2018-01-08 17:28 UTC
This can be seen by trying out the gvr-controller demo app using just the gaze controller and tapping the touchpad on the headset.

Picking up and releasing the objects is very erratic, the first pick up seems to work, but after that releasing it is erratic, sometimes it can be done after multiple taps. Other times once I've picked up an object I can't drop it even with repeated taps, but if I bump it into other objects the pick may automatically transfer to the other object and that starts moving instead.

**Comment by NolaDonato** [comment] 2018-01-09 02:31
I am not able to reproduce this issue. I am using the S8. I do notice that if the phone is not properly docked in the headset I cannot select anything at all with the touchpad.  What phone are you using?

**Comment by SteveGreatApe** [comment] 2018-01-09 07:58
It's a Samsung Galaxy S7 I'm using.

I've stuck a few breakpoints in to help track down what's wrong. I can see that in GVRGazeCursorController.handleMotionEvent() it's not receiving the MotionEvent.ACTION_UP events when the problem occurs. The MotionEvent.ACTION_DOWN events are coming through reliably every time I touch the touchpad, but the corresponding MotionEvent.ACTION_UP events are only occasionally received, so the system thinks I'm still touching the pad when that happens.

**Comment by NolaDonato** [comment] 2018-01-09 22:07
I will test this on other phones to see if I can reproduce it. My S8 is rock solid on touch when it is inserted correctly in the headset.

**Comment by NolaDonato** [comment] 2018-01-10 23:50
I have also tried the S7 and I cannot reproduce it. Can you tell me a bit more about your phone. Maybe your software needs updating? My model number is SM-G930V. What is yours? I am running Android version 7.0 and my kernel version is 3.18.31.

**Comment by SteveGreatApe** [comment] 2018-01-16 09:41
This one has me confused, I think there's now two seperate issues. Originally I could reproduce on the master branch, but not on Nola's controller_fixes_4.1 branch. Then the problem started to occur on that branch so I stuck some logging into GVRGazeCursorController

```
        private void handleMotionEvent(MotionEvent event)
        {
            float eventX = event.getX();
            float eventY = event.getY();
            float eventZ;
            int action = event.getAction();
            float deltaX;

            Log.d("ZZZ:handleMotionEvent", "action=" + action + ", mTouchButtons=" + mTouchButtons + ", getButtonState()=" + event.getButtonState());
            switch (action)
```

It found this sequence:
```
01-15 16:11:25.810 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=0, mTouchButtons=3, getButtonState()=1
01-15 16:11:25.835 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=11, mTouchButtons=3, getButtonState()=1
01-15 16:11:25.862 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=2, mTouchButtons=3, getButtonState()=1
01-15 16:11:25.890 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=2, mTouchButtons=3, getButtonState()=1
...
01-15 16:11:26.547 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=2, mTouchButtons=3, getButtonState()=1
01-15 16:11:26.651 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=12, mTouchButtons=3, getButtonState()=0
01-15 16:11:26.667 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=1, mTouchButtons=3, getButtonState()=0
01-15 16:11:26.679 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=9, mTouchButtons=3, getButtonState()=0
01-15 16:11:26.685 32719-334/org.gearvrf.sample.controller D/ZZZ:handleMotionEvent: action=7, mTouchButtons=3, getButtonState()=0
```
The critical bit is
`handleMotionEvent: action=1, mTouchButtons=3, getButtonState()=0`

because setActive(false) doesn't get called unless getButtonState() matches with mTouchButtons. This simply looks like a bug in the new change to configure which buttons create the touch event.

```
                case MotionEvent.ACTION_UP:
                if ((mTouchButtons & event.getButtonState()) != 0)
                {
                    setActive(false);
                }
                setKeyEvent(BUTTON_GAZE_UP);
                break;

```

But the thing is, I reported this bug before that change was made, so I added a similar logging line into the Master branch and got this:
```
First touch
01-16 09:31:59.631 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=0, getButtonState()=1
01-16 09:31:59.649 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=11, getButtonState()=1
01-16 09:31:59.680 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:31:59.715 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:31:59.740 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:31:59.752 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:31:59.780 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.431 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.454 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.498 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.528 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.540 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:00.563 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=9, getButtonState()=0
01-16 09:32:00.576 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:32:00.604 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:32:00.619 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
...
Second touch
01-16 09:32:21.042 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=10, getButtonState()=1
01-16 09:32:21.067 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=11, getButtonState()=1
01-16 09:32:21.112 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:21.145 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:21.779 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:32:21.839 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:32:21.859 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:32:21.888 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:32:21.900 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
```
Note the first touch starts with action=0 (ACTION_DOWN) and has no corresponding action=1 (ACTION_UP), and second one starts with with action=11 (ACTION_BUTTON_PRESS)

I did later get an ACTION_UP event through with this sequence
```
01-16 09:36:13.179 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=10, getButtonState()=1
01-16 09:36:13.197 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=11, getButtonState()=1
01-16 09:36:13.225 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:36:13.238 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:36:13.265 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:36:13.279 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=2, getButtonState()=1
01-16 09:36:13.683 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=1, getButtonState()=0
01-16 09:36:13.700 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:36:13.712 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
01-16 09:36:13.738 22520-23522/org.gearvrf.sample.controller D/ZZZ2:handleMotionEvent: action=7, getButtonState()=0
```
But these are erratic and only occasionally come through. As far as I can tell this missing ACTION_UP bug doesn't occur on Nola's branch, so it might be fixed there, or maybe it's just luck with timing that I'm not hitting it.

**Comment by NolaDonato** [comment] 2018-01-17 22:11
Are you saying that sometimes the ACTION_UP coming from Android doesn't have the right button state and that sometimes we never get the ACTION_UP for buttonstate 1 but instead get ACTION_UP for buttonstate 0?

**Comment by SteveGreatApe** [comment] 2018-01-18 14:17
On the main master repo most of the time the ACTION_UP event never comes through.

On your controller_fixes_4.1 branch ACTION_UP  events come through reliably, but your recent change adding the 'mTouchButtons' functionality seems to assume the button state would set in the ACTION_UP event, which seems wrong to me as the button is now up, so the state shouldn't show it as set.

**Comment by NolaDonato** [comment] 2018-01-18 19:34
Ok I will change that

**Comment by NolaDonato** [comment] 2018-01-18 21:04
I pushed a change to the pull request that ignores the button state on ACTION_UP. Let me know if that works for you.

**Comment by NolaDonato** [comment] 2018-02-06 20:50
Are you still having this problem or can I close this issue?

**Comment by SteveGreatApe** [comment] 2018-02-07 11:24
Seems fine running on your branch, hopefully when you merge that into the master branch that will also be fixed.

**Comment by NolaDonato** [comment] 2018-02-08 08:36
PR #1646 has been merged into the master.

**Closed** 2018-02-15 23:50 UTC
Labels: bug
