### ISSUE TITLE
Possible bug report: showLoadingIcon

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#645] opened 2016-06-27 18:10 UTC
I was setting `showLoadingIcon="true"` to `false` on the configuration file, and noticed my app doesn't show anything. Maybe that is a bug?

**Comment by liaxim** [comment] 2016-06-27 18:27
The problem is that our splash screen support is not transparent to end users. If you want a splash screen you need to use getNextMainScene to get the main scene. If you are not using a splash screen then you should use getMainScene. We will correct this in the near future.

I assume you usually have a splash screen so you are using getNextMainScene. If you turn off the splash screen then this is no longer the right scene to add your scene objects to. Does my explanation make sense?

**Comment by arianaa30** [comment] 2016-06-27 18:32
It makes sense. Anyways, I'm fine with having the splash screen:)

**Comment by liaxim** [comment] 2016-06-27 18:37
So can we close the issue? We are tracking the api deficiency in https://github.com/Samsung/GearVRf/issues/439.

**Comment by arianaa30** [comment] 2016-06-27 18:42
Yes. Go ahead.
One basic problem that I have is I can not run my sample projects by referencing `Framework` project or adding it's generated `.jar` file into my project. I am using the `gvr-exported.jar` file that Thomas  gave me when I was starting (which seems an older version). 
Is there a newer version, or maybe you can help me with the project referencing issue?

**Comment by liaxim** [comment] 2016-06-27 18:48
Let me know the errors you get.

If you import the Framework project in Eclipse and it builds successfully you should have no problems once you add the Framework project under Project Properties->Android->Library of your app.

If you want to try to build the Framework yourself we have the instructions here: http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct

**Comment by arianaa30** [comment] 2016-06-27 22:21
And when using the project reference method instead of copying the .jar file, here is the error which seems different:

```
06-27 15:19:50.184: E/AndroidRuntime(24206): FATAL EXCEPTION: main
06-27 15:19:50.184: E/AndroidRuntime(24206): Process: org.gearvrf.gvr360video, PID: 24206
06-27 15:19:50.184: E/AndroidRuntime(24206): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.gearvrf.gvr360video/org.gearvrf.gvr360video.Minimal360VideoActivity}: java.lang.ClassNotFoundException: Didn't find class "org.gearvrf.gvr360video.Minimal360VideoActivity" on path: DexPathList[[zip file "/data/app/org.gearvrf.gvr360video-2/base.apk"],nativeLibraryDirectories=[/data/app/org.gearvrf.gvr360video-2/lib/arm, /data/app/org.gearvrf.gvr360video-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.os.Looper.loop(Looper.java:158)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread.main(ActivityThread.java:7229)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at java.lang.reflect.Method.invoke(Native Method)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-27 15:19:50.184: E/AndroidRuntime(24206): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.gearvrf.gvr360video.Minimal360VideoActivity" on path: DexPathList[[zip file "/data/app/org.gearvrf.gvr360video-2/base.apk"],nativeLibraryDirectories=[/data/app/org.gearvrf.gvr360video-2/lib/arm, /data/app/org.gearvrf.gvr360video-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3084)
06-27 15:19:50.184: E/AndroidRuntime(24206): 	... 9 more
06-27 15:19:50.184: E/AndroidRuntime(24206): 	Suppressed: java.lang.NoClassDefFoundError: org.gearvrf.gvr360video.Minimal360VideoActivity
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at dalvik.system.DexFile.defineClassNative(Native Method)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		... 13 more
06-27 15:19:50.184: E/AndroidRuntime(24206): 	Suppressed: java.lang.ClassNotFoundException: org.gearvrf.gvr360video.Minimal360VideoActivity
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at java.lang.Class.classForName(Native Method)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-27 15:19:50.184: E/AndroidRuntime(24206): 		... 12 more
06-27 15:19:50.184: E/AndroidRuntime(24206): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

**Comment by liaxim** [comment] 2016-06-27 22:37
For the "closed unexpected" problem - you should use a project reference since the Framework is a library project and the Android plugin for Eclipse handles things for you.

**Comment by arianaa30** [comment] 2016-06-27 22:41
For both I get "closed unexpectedly" error.

**Comment by liaxim** [comment] 2016-06-27 22:47
About the second problem the only thing I can think of is that the sample is not actually building successfully. You can easily produce broken apk with Eclipse actually.

Please make sure you don't have any local changes in your git repos; then do a git clean -fd to remove any untracked files; then import the projects in Eclipse and build again. Send me the complete logcat output if there are problems. You could also enable verbose build logs in Eclipse by going to Window->Preferences->Android->Build and choosing verbose build output.

**Comment by arianaa30** [comment] 2016-06-27 22:50
Well, I'm not using git. I downloaded the whole source as a zip file and extracted it, and followed the instruction on the website (placing Oculus mobile sdk and stuff). The project builds successfully though.

**Comment by liaxim** [comment] 2016-06-28 14:35
Without more information I can't really help. I am pretty sure the samples can be built with both Android Studio and Eclipse.

It might be easier for you if you start from scratch to ensure you are working without any local modifications.

**Comment by arianaa30** [comment] 2016-06-28 23:33
OK. I will download a fresh copy from copy and import it. I'll update you on that.
If you want you can close this issue as this topic is unrelated.

**Comment by liaxim** [comment] 2016-06-29 14:27
Thank you. Let us know if you still have problems.

**Closed by liaxim** 2016-06-29 14:27 UTC
Labels: build issue
