### ISSUE TITLE
Monoscopic mode not supported now?

### ISSUE THREAD

**Issue by rongguodong** [Samsung/GearVRf#256] opened 2015-09-18 00:30 UTC
With the latest pull, I cannot run any sample on my Nexus 5 phone. (Previously I can run all samples in monoscopic mode)

From the adb logcat, I can see
ovr_StartSystemActivity: failMenu {
    "extraData":	{
        "Reason":	"failOSig",
        "Tag":	"VrApi",
        "Message":	"Thread priority security exception. Make sure the APK is signed."
    }
}

But I already have a signature file in asset folder. Do we still support monoscopic mode on non-Samsung phones now?

**Comment by thomasflynn** [comment] 2015-09-18 00:34
it should work.  and you shouldn't need a signature if you're on a non-samsung phone anyway.  we did recently upgrade to version 0.6.2 of the oculus mobile sdk.  maybe something changed then?  gimme a few minutes and i'll try on my S5....

**Comment by rongguodong** [comment] 2015-09-18 00:37
It broken after the change to 0.6.1, and is still bad after 0.6.2. :(

**Comment by thomasflynn** [comment] 2015-09-18 01:08
ok, i can reproduce the problem.  i don't have a suggestion for a work-around yet.  need to better understand what they changed.  seems like the point where vrapi_Initialize gets called got moved maybe.

**Comment by thomasflynn** [comment] 2015-09-18 02:34
it seems to be happening inside the nativeOnCreate of VrActivity.  i think we need to stop using VrAppFramework and just use VrApi directly.  that way we don't need to derive from VrActivity and we'll have more control over when things get initialized.  That'll be a non-trivial port.  Probably worth doing though.

**Comment by thomasflynn** [comment] 2015-09-21 02:30
another approach would be to have GVRActivity be a proxy activity of some sort and have it create and route events to the VrActivity when we decide to do so.  I took a closer look at the VrApi this past weekend.  It's definitely the right long term way to go.  It would be a fairly significant change though.

**Comment by thomasflynn** [comment] 2015-10-12 18:01
FWIW, I took a stab at the hacky solution over the weekend.  I couldn't get it to work again with Oculus although it looks like it theoretically should.  Seems to fail inside native code inside the Oculus libs looking to call back into Java.  I've obviously missed something.

If you're interested, take a look.  Maybe debug it :)  I'll be going on PTO soon and I likely won't have time to hack at this again for a couple of weeks: 
https://github.com/thomasflynn/GearVRf/tree/vractivity

**Comment by liaxim** [comment] 2015-10-27 20:14
@thomasflynn I looked at your branch and my take is that this is unlikely to ever work. An Android activity is supposed to be instantiated by the runtime and the runtime sets up state behind the scenes (Activity.attach() for example) that we simply cannot replicate. So even though it seems like you have an Oculus activity instance, it only seems like it as the Android framework has not set it up.

What I am pretty sure would work is using an intermediate detector Activity. Before elaborating further I must mention that this would make the app manifest more complicated and will require developers willing to support monoscopic rendering implement yet another Activity.

Basically the manifest of an app supporting Oculus and Monoscopic will require three activities:

1. Detector activity - supplied by the framework and configured to route to user supplied Activities 2. and 3. This activity will determine whether Oculus is supported on this phone and startActivity 2. if it is or 3. if not. This activity will be the one launched when clicking the app's icon in the launcher.
2. Activity for phones supporting Oculus that would derive from our GVROculusActivity (more or less our existing GVRActivity).
3. Activity for the rest of the phones deriving from GVRMonoscopicActivity (GVRActivity stripped down to just what is needed for monoscopic rendering).

This is somewhat ugly but doable. It's pros and cons should be weighed against using the VrApi before deciding to proceed with it. I think though even with the use of VrApi GVRF will benefit by compartmentalizing the Oculus dependency.

**Comment by danke-sra** [comment] 2015-11-12 07:34
The suggested approach is not ugly at all. It gives us a way to start either GVROculusActivity or the GVRMonoscopicActivity, and they don't have any inter-dependencies. This approach is indeed sometimes used in Android. The Activity in 2 or 3 needs to be started with an Intent with the flag FLAG_ACTIVITY_NO_HISTORY. I think this approach will work.

**Comment by liaxim** [comment] 2015-11-12 15:56
The "ugly" part for me is the burden on the end user - they need to derive from yet another activity if they would like to support mono. Not much but they are exposed to yet another thing.

**Comment by thomasflynn** [comment] 2016-02-18 03:17
we have a port on top of VrApi now.  Please test:  https://github.com/Samsung/GearVRf/pull/412

**Comment by liaxim** [comment] 2016-03-10 15:48
Monoscopic works now. Can we close this issue?

**Closed** 2016-03-18 16:42 UTC
