### ISSUE TITLE
Particles start freezing after 3min

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1482] opened 2017-09-28 22:35 UTC
Hi all,
I am trying to use the GVRPlaneEmitter but after 3min the particles start to freeze!

The same behavior you can see at gvr-particles demo.

Does anybody could help me about this?

**Comment by liaxim** [comment] 2017-09-29 14:11
I will take a look.

**Comment by bohuang3d** [comment] 2017-09-29 16:54
@ragner how many particles before they freeze in place? Just the particle freezes not the app right?

**Comment by liaxim** [comment] 2017-09-29 18:58
@ragner Is it always reproducible? Could you attach logs? It is yet to reproduce for me (S8).

**Comment by ragner** [comment] 2017-09-29 21:03
Hi @all,
yes it is always reproducible. You can see this issue at gvr-particles demo from GVRf-Demos repository.

@bohuang3d,
yes, just the particles freezes ... the other scene objects continue rendering well. The app does not freeze.

It look like a shader issue but I did not find the cause ;(

**Comment by liaxim** [comment] 2017-10-03 17:38
I am not able to reproduce.

**Comment by ragner** [comment] 2017-10-03 17:57
@liaxim,
if you do any touch it resets the particle system and the bug is not reproducible ...

You should launch the particles demo  and wait for +- 3min to see this issue

**Comment by liaxim** [comment] 2017-10-03 18:10
Will try again

**Comment by liaxim** [comment] 2017-10-03 22:37
Does it gradually get slower and slower? This is what I am noticing on S7 although it hasn't completely stopped yet for me. I guess on S8 it would just take a lot longer than 3 min before the "Big Freeze".

**Comment by ragner** [comment] 2017-10-03 22:45
@liaxim  yes, 
it gets slower and slower ... It does not freeze completely.
But the applications continues rendering with 60 fps ...

**Comment by liaxim** [comment] 2017-10-04 18:17
Something about the total time. Once it gets big enough everything seems to slow down.

**Comment by dnvasilev** [comment] 2017-10-04 19:37
currentTime is long, but onDrawFrame time parameter is float. float has low precision (10e-7). For accurate callbacks, precision must be above 10 ms; float frameTime must be less than 10000s, or about 3 hours since boot.

**Comment by dnvasilev** [comment] 2017-10-04 20:14
Easy fix, breaking a lot of code: onDrawFrame(long)
Compatible fix: deprecate GVRDrawFrameListener, create new interface with new name declaring onDrawFrame(long), create new registerDrawFrameListener() methods (deprecate old ones), etc.etc.etc.

**Comment by liaxim** [comment] 2017-10-04 20:52
@ragner Another easy, but not cheap fix: https://github.com/Samsung/GearVRf/pull/1496. Works for me pretty well on S7. Tried with some pretty large totalTimes though probably there is a point it will break too.

**Comment by ragner** [comment] 2017-10-04 21:40
@liaxim, thank you. I will try it.

**Comment by liaxim** [comment] 2017-10-23 17:52
Fixed by #1496

**Closed by liaxim** 2017-10-23 17:52 UTC
Labels: bug
