### ISSUE TITLE
Possible bug with loadModel()

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#461] opened 2016-03-10 18:58 UTC
I've created a simplified version of an issue I found while loading FBX models in GVRf. Below is a modified version of simple-sample that highlights the problem:

https://github.com/rahul27/GearVRf-Demos/commit/f644c382e7c1484eb6929c076452a50d7f8752ad

The app is supposed to load 40 instances of the same object in 10 rows but I only see 4 rows. However, if you delete the texture file from the sample then you will see all the models load correctly.

**Comment by danke-sra** [comment] 2016-03-10 19:38
Thanks for narrowing down the problem to textures. We fixed some issues about that recently but seems there are still some problems.

**Comment by danke-sra** [comment] 2016-03-10 19:48
@mingsong @NolaDonato Are any of you interested in looking at this issue? If not, I will do it when I get a chance, but it seems related to some other issues you solved.

**Comment by mingsong** [comment] 2016-03-10 20:06
@rahul27, What do you mean by "deleting the texture file then it loads correctly"?
I will take a look at it but I need to know some details.

**Comment by mingsong** [comment] 2016-03-12 01:13
The problem is due to the async loading of resources, when use sync loading for jassimp loader, all models and textures loaded well. More specifically, the thread pool is deadlocked in this case, that after first 16 loading tasks out of the total 40 finishes, the next 16 are expected to come in. However since we use Material::setTexture(FutureTexture) which creates another 16 pending tasks waiting for the futureTexture loading, and upperlimit for our threadpool is set to 16 currently, meaning that all threads in the pool are taken by those pending tasks and no more loading tasks are allowed to be executed to release those pending threads. From this point of time on, we can no longer execute ANY task on the thread pool actually.  My current solution is to change the use mechanism of a futureResource: instead of creating a new runnable pending for the resource, create a callback to hook up to the resource. Since the Throttler already provides a resource pending queue to provide the callback functionality, this change can take this structure a free ride.

**Comment by danke-sra** [comment] 2016-03-17 21:49
Fixed by https://github.com/Samsung/GearVRf/pull/470

**Closed** 2016-03-18 16:41 UTC
